/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.intellibitz.mobile.dating;

public final class R {
    public static final class array {
        public static final int menu=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_sample_code=0x7f020000;
        public static final int boy_and_girl=0x7f020001;
        public static final int datingicon=0x7f020002;
        public static final int hello=0x7f020003;
        public static final int icon1=0x7f020004;
        public static final int icon11=0x7f020005;
        public static final int icon2=0x7f020006;
        public static final int icon3=0x7f020007;
        public static final int icon4=0x7f020008;
        public static final int icon5=0x7f020009;
        public static final int icon6=0x7f02000a;
        public static final int no_picture=0x7f02000b;
        public static final int stat_happy=0x7f02000c;
        public static final int stat_neutral=0x7f02000d;
        public static final int stat_sad=0x7f02000e;
        public static final int stat_sample=0x7f02000f;
    }
    public static final class id {
        public static final int Age=0x7f06000a;
        public static final int Height=0x7f06000e;
        public static final int Location=0x7f060010;
        public static final int Weight=0x7f06000f;
        public static final int back=0x7f06001e;
        public static final int buttonActivate=0x7f060007;
        public static final int buttonBack=0x7f060008;
        public static final int chatmessage=0x7f060000;
        public static final int clear=0x7f060012;
        public static final int dreamlabelage=0x7f060014;
        public static final int dreamlabelsex=0x7f060016;
        public static final int femaleradiobutton=0x7f06000d;
        public static final int happy=0x7f06001f;
        public static final int label=0x7f060009;
        public static final int labelheight=0x7f060017;
        public static final int labellocation=0x7f06001b;
        public static final int labelweight=0x7f060019;
        public static final int listmessage=0x7f060006;
        public static final int maleradiobutton=0x7f06000c;
        public static final int message=0x7f060001;
        public static final int neutral=0x7f060020;
        public static final int partnerAge=0x7f060015;
        public static final int partnerHeight=0x7f060018;
        public static final int partnerLocation=0x7f06001c;
        public static final int partnerWeight=0x7f06001a;
        public static final int sad=0x7f060021;
        public static final int send=0x7f06001d;
        public static final int submit=0x7f060004;
        public static final int submit1=0x7f060011;
        public static final int txtNewMessage=0x7f060003;
        public static final int type=0x7f060002;
        public static final int type1=0x7f060005;
        public static final int welcome=0x7f060013;
        public static final int widget0=0x7f060027;
        public static final int widget125=0x7f060022;
        public static final int widget126=0x7f060023;
        public static final int widget127=0x7f060024;
        public static final int widget128=0x7f060025;
        public static final int widget208=0x7f060026;
        public static final int widget27=0x7f060028;
        public static final int widget28=0x7f060029;
        public static final int widget29=0x7f06000b;
        public static final int widget30=0x7f06002a;
    }
    public static final class layout {
        public static final int chat=0x7f030000;
        public static final int dating_controller=0x7f030001;
        public static final int main=0x7f030002;
        public static final int partner=0x7f030003;
        public static final int status_bar_notifications=0x7f030004;
        public static final int welcome=0x7f030005;
        public static final int welcomeprofile=0x7f030006;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int local_service_started=0x7f050012;
        public static final int local_service_stopped=0x7f050013;
        public static final int notifying_service_controller=0x7f050002;
        public static final int start_service=0x7f050003;
        public static final int status_bar_chennai=0x7f050005;
        public static final int status_bar_coimbatore=0x7f050008;
        public static final int status_bar_erode=0x7f05000c;
        public static final int status_bar_madurai=0x7f05000d;
        public static final int status_bar_nellai=0x7f05000e;
        public static final int status_bar_notifications_clear=0x7f050009;
        public static final int status_bar_notifications_icons_and_marquee=0x7f05000f;
        public static final int status_bar_notifications_icons_only=0x7f05000b;
        public static final int status_bar_notifications_mood_title=0x7f05000a;
        public static final int status_bar_notifications_ok_message=0x7f050007;
        public static final int status_bar_notifications_remote_views=0x7f050010;
        public static final int status_bar_salem=0x7f050006;
        public static final int stop_service=0x7f050004;
        public static final int userinfo=0x7f050011;
        public static final int welcome=0x7f050001;
    }
}
