application: fyteklub
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /admin/.*
  script: main.py
  login: admin

- url: /webedit/.*
  script: main.py
  login: admin

- url: /secure/.*
  script: main.py
  secure: always

- url: /.*
  script: main.py
