/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mobeegal.android;

public final class R
{
    public static final class array
    {
        public static final int Audi = 0x7f05002a;
        public static final int BMW = 0x7f05002c;
        public static final int Bentley = 0x7f05002b;
        public static final int Chevrolet = 0x7f05002d;
        public static final int ChooseCategory = 0x7f05000c;
        public static final int Chrysler = 0x7f05002e;
        public static final int Color = 0x7f050050;
        public static final int CookingMethod = 0x7f050017;
        public static final int Daewoo = 0x7f05002f;
        public static final int DieteticConsiderations = 0x7f050018;
        public static final int Ferrari = 0x7f050030;
        public static final int Fiat = 0x7f050031;
        public static final int Ford = 0x7f050032;
        public static final int FuelType = 0x7f050051;
        public static final int HindustanMotors = 0x7f050033;
        public static final int Honda = 0x7f050034;
        public static final int Hummer = 0x7f050035;
        public static final int Hyundai = 0x7f050036;
        public static final int ICML = 0x7f050037;
        public static final int Lamborghini = 0x7f050038;
        public static final int LandRover = 0x7f050039;
        public static final int Lexus = 0x7f05003a;
        public static final int Mahindra = 0x7f05003b;
        public static final int MahindraRenault = 0x7f05003c;
        public static final int MainIngredient = 0x7f05001b;
        public static final int Maini = 0x7f05003d;
        /**
         * <<<<<<<<<<<<<<<<<< Car Attribute Values >>>>>>>>>>>>>>>>>>>>>>
         */
        public static final int MakeType = 0x7f050029;
        public static final int Maruti = 0x7f05003e;
        public static final int Maserati = 0x7f05003f;
        public static final int Maybach = 0x7f050040;
        public static final int Mercedes = 0x7f050041;
        public static final int Miscellaneous = 0x7f05001d;
        public static final int Mitsubishi = 0x7f050042;
        public static final int MovieLanguage = 0x7f05001f;
        /**
         * <<<<<<<<<<<<<<<<<<<<<<<<<<<<<Movies Attributes >>>>>>>>>>>>>>>>>>>>>>>>>>>
         */
        public static final int MovieType = 0x7f05001e;
        public static final int Nissan = 0x7f050043;
        public static final int OccasionOrSeason = 0x7f05001c;
        public static final int Opel = 0x7f050044;
        public static final int Peugeot = 0x7f050045;
        public static final int Porsche = 0x7f050046;
        public static final int Price = 0x7f050052;
        public static final int RollsRoyce = 0x7f050047;
        public static final int SanMotors = 0x7f050048;
        public static final int SeatingStyle = 0x7f050020;
        public static final int Sipani = 0x7f050049;
        public static final int Skoda = 0x7f05004a;
        public static final int Tata = 0x7f05004b;
        public static final int Toyota = 0x7f05004c;
        public static final int TypeofCourse = 0x7f050019;
        /**
         * jewlery closed <<<<<<<<<<<<<<<<<<<<<<<<<< Restaurents
         * >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
         */
        public static final int TypeofCuisine = 0x7f050016;
        public static final int TypeofDish = 0x7f05001a;
        public static final int Volkswagen = 0x7f05004d;
        public static final int Volvo = 0x7f05004e;
        public static final int Year = 0x7f05004f;
        public static final int age = 0x7f050008;
        public static final int fileEndingAudio = 0x7f050055;
        public static final int fileEndingImage = 0x7f050054;
        public static final int fileEndingPackage = 0x7f050057;
        public static final int fileEndingVideo = 0x7f050056;
        public static final int fileEndingWebText = 0x7f050058;
        public static final int height = 0x7f050009;
        public static final int iStuffChrstian = 0x7f050005;
        public static final int iStuffMiscellaneous = 0x7f050022;
        public static final int iStuffRate = 0x7f050025;
        /**
         * <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Rental Attributes>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
         */
        public static final int iStuffRentalType = 0x7f050021;
        public static final int iStuffStatus = 0x7f050023;
        public static final int iStuffage = 0x7f050000;
        public static final int iStuffcolor = 0x7f05000d;
        public static final int iStuffheight = 0x7f050001;
        public static final int iStuffweight = 0x7f050002;
        public static final int istuffhindu = 0x7f050004;
        public static final int istuffmuslim = 0x7f050006;
        public static final int istuffreligion = 0x7f050003;
        public static final int istuffsikh = 0x7f050007;
        public static final int istuffweightingram = 0x7f050014;
        public static final int jewelrygender = 0x7f050011;
        /**
         * jewelry
         */
        public static final int jewelrytype = 0x7f050010;
        public static final int metaltype = 0x7f050013;
        public static final int selecttheme = 0x7f050053;
        public static final int stonetype = 0x7f050012;
        public static final int timeperiod = 0x7f05000b;
        public static final int uStuffMiscellaneous = 0x7f050027;
        public static final int uStuffRate = 0x7f050028;
        public static final int uStuffRentalType = 0x7f050026;
        public static final int uStuffStatus = 0x7f050024;
        public static final int uStuffcolor = 0x7f05000e;
        public static final int ustuffreligion = 0x7f05000f;
        public static final int ustuffweightingram = 0x7f050015;
        public static final int weight = 0x7f05000a;
    }

    public static final class attr
    {
    }

    public static final class drawable
    {
        public static final int about_enabled = 0x7f020000;
        public static final int about_focused = 0x7f020001;
        public static final int about_orange = 0x7f020002;
        public static final int about_unfocused = 0x7f020003;
        public static final int activate_deactivate = 0x7f020004;
        public static final int addasfavorites = 0x7f020005;
        public static final int audio = 0x7f020006;
        public static final int blue = 0x7f020039;
        public static final int bubble = 0x7f020007;
        public static final int bubble1 = 0x7f020008;
        public static final int cancel = 0x7f020009;
        public static final int cars_icon = 0x7f02000a;
        public static final int catalogs = 0x7f02000b;
        public static final int chat = 0x7f02000c;
        public static final int chat1 = 0x7f02000d;
        public static final int dating_icon = 0x7f02000e;
        public static final int even_stripe = 0x7f020037;
        public static final int favorites = 0x7f02000f;
        public static final int folder = 0x7f020010;
        public static final int goroot = 0x7f020011;
        public static final int helpsettings = 0x7f020012;
        public static final int icon = 0x7f020013;
        public static final int ignore = 0x7f020014;
        public static final int image = 0x7f020015;
        public static final int info = 0x7f020016;
        public static final int istuff = 0x7f020017;
        public static final int jewelry_icon = 0x7f020018;
        public static final int marker = 0x7f020019;
        public static final int matrimony_icon = 0x7f02001a;
        public static final int media = 0x7f02001b;
        public static final int message = 0x7f02001c;
        public static final int mobeegal = 0x7f02001d;
        public static final int mobeegal1 = 0x7f02001e;
        public static final int mobeegalicon = 0x7f02001f;
        public static final int mobeegalservice = 0x7f020020;
        public static final int movies_icon = 0x7f020021;
        public static final int mstuff = 0x7f020022;
        public static final int nav_bar_left_arrow = 0x7f020023;
        public static final int nav_bar_right_arrow = 0x7f020024;
        public static final int no_picture = 0x7f020025;
        public static final int odd_stripe = 0x7f020038;
        public static final int ok = 0x7f020026;
        public static final int packed = 0x7f020027;
        public static final int preference = 0x7f020028;
        public static final int rental_icon = 0x7f020029;
        public static final int restaurant_icon = 0x7f02002a;
        public static final int select_icon = 0x7f02002b;
        public static final int settings = 0x7f02002c;
        public static final int shadow = 0x7f02002d;
        public static final int stat_sample = 0x7f02002e;
        public static final int text = 0x7f02002f;
        public static final int uponelevel = 0x7f020030;
        public static final int user = 0x7f020031;
        public static final int ustuff = 0x7f020032;
        public static final int video = 0x7f020033;
        public static final int webtext = 0x7f020034;
        public static final int zoomin = 0x7f020035;
        public static final int zoomout = 0x7f020036;
    }

    public static final class id
    {
        public static final int Areanotfound = 0x7f0700c9;
        public static final int FoodType = 0x7f070029;
        public static final int Locationbroadcasting = 0x7f0700a5;
        public static final int Misc = 0x7f07002a;
        public static final int Misc1 = 0x7f070031;
        public static final int MovieArea = 0x7f070034;
        public static final int MovieCity = 0x7f070033;
        public static final int MovieCountry = 0x7f070032;
        public static final int MovieDetails = 0x7f07002e;
        public static final int MovieType = 0x7f070030;
        public static final int Movies = 0x7f07002f;
        public static final int Rental = 0x7f070038;
        public static final int Restaurant = 0x7f070027;
        public static final int Save = 0x7f070019;
        public static final int Set = 0x7f0700ce;
        public static final int activate_deactivate = 0x7f0700be;
        public static final int activateradiobutton = 0x7f0700cf;
        public static final int agespinner1 = 0x7f070088;
        public static final int auto = 0x7f0700a7;
        public static final int autoradiobutton = 0x7f0700a2;
        public static final int back = 0x7f070036;
        public static final int basic = 0x7f07007d;
        public static final int buttonActivate = 0x7f070020;
        public static final int buttonBack = 0x7f070021;
        public static final int catalogimgupload = 0x7f070094;
        public static final int catalogmedia = 0x7f070093;
        public static final int chat = 0x7f070063;
        public static final int deactivateradiobutton = 0x7f0700d0;
        public static final int details = 0x7f070092;
        public static final int detailstext = 0x7f07005b;
        public static final int done = 0x7f070042;
        public static final int dreamlabelsex = 0x7f070089;
        public static final int favorites = 0x7f070061;
        public static final int filters = 0x7f07008c;
        public static final int gallery = 0x7f070035;
        public static final int help = 0x7f070037;
        public static final int helpsettings = 0x7f0700c0;
        public static final int hintlayout = 0x7f07005e;
        public static final int hinttext = 0x7f07005f;
        public static final int hitlayout = 0x7f07005c;
        public static final int hittext = 0x7f07005d;
        public static final int home_container = 0x7f0700c1;
        public static final int iStuffColor = 0x7f070007;
        public static final int iStuffCookingMethod = 0x7f0700ae;
        public static final int iStuffCourseType = 0x7f0700b0;
        public static final int iStuffCuisinetype = 0x7f0700ad;
        public static final int iStuffDietetic = 0x7f0700af;
        public static final int iStuffDishType = 0x7f0700b1;
        public static final int iStuffFuelType = 0x7f070008;
        public static final int iStuffMainIngredient = 0x7f0700b2;
        public static final int iStuffMake = 0x7f070003;
        public static final int iStuffMisc = 0x7f07003a;
        public static final int iStuffMiscellaneous = 0x7f0700b4;
        public static final int iStuffModel = 0x7f070004;
        public static final int iStuffOccasionOrSeason = 0x7f0700b3;
        public static final int iStuffPrice = 0x7f070009;
        public static final int iStuffRate = 0x7f07003b;
        public static final int iStuffRentalType = 0x7f070039;
        public static final int iStuffStatus = 0x7f07003c;
        public static final int iStuffYear = 0x7f070006;
        public static final int iStuffage = 0x7f07006b;
        public static final int iStuffcaste = 0x7f07006a;
        public static final int iStuffcolor = 0x7f070072;
        public static final int iStufffemaleradiobutton = 0x7f07006e;
        public static final int iStuffgender = 0x7f070046;
        public static final int iStuffheight = 0x7f070070;
        public static final int iStuffitemtype = 0x7f070044;
        public static final int iStuffmaleradiobutton = 0x7f07006d;
        public static final int iStuffmetaltype = 0x7f070049;
        public static final int iStuffmovielanguage = 0x7f070083;
        public static final int iStuffmovietype = 0x7f070082;
        public static final int iStuffprofile = 0x7f070001;
        public static final int iStuffreligion = 0x7f070069;
        public static final int iStuffstonetype = 0x7f070048;
        public static final int iStuffweight = 0x7f07004c;
        public static final int iarea = 0x7f07000b;
        public static final int icity = 0x7f07000c;
        public static final int iconslayout = 0x7f070060;
        public static final int icountry = 0x7f07000d;
        public static final int ignore = 0x7f070062;
        public static final int image = 0x7f07007b;
        public static final int latandlong = 0x7f070052;
        public static final int layout = 0x7f07005a;
        public static final int layout_map = 0x7f070058;
        public static final int layout_zoom = 0x7f070059;
        public static final int mStuffView = 0x7f07009d;
        public static final int manual = 0x7f0700a8;
        public static final int manualradiobutton = 0x7f0700a3;
        public static final int map = 0x7f070055;
        public static final int mapSearch = 0x7f07008f;
        public static final int map_location_viewer = 0x7f0700c2;
        public static final int mapviewradiobutton = 0x7f07009f;
        public static final int media = 0x7f070064;
        public static final int modegroup = 0x7f07007c;
        public static final int modeno = 0x7f070081;
        public static final int modeyes = 0x7f070080;
        public static final int mostpopular = 0x7f07001d;
        public static final int myGrid = 0x7f07001b;
        public static final int myGrid1 = 0x7f070022;
        public static final int myTableLayout = 0x7f070043;
        public static final int otherpopular = 0x7f07001f;
        public static final int pause = 0x7f07009a;
        public static final int play = 0x7f070099;
        public static final int popular = 0x7f07001e;
        public static final int preference = 0x7f0700bf;
        public static final int premium = 0x7f07007f;
        public static final int recipient = 0x7f070023;
        public static final int res = 0x7f0700ac;
        public static final int resArea = 0x7f07002d;
        public static final int resCity = 0x7f07002c;
        public static final int resCountry = 0x7f07002b;
        public static final int resume = 0x7f07009b;
        public static final int save = 0x7f0700ab;
        public static final int savinglocation = 0x7f070054;
        public static final int searchButton = 0x7f07008e;
        public static final int searchMstuff = 0x7f07008d;
        public static final int selectall = 0x7f0700c3;
        public static final int selectistufflocation = 0x7f07000a;
        public static final int selectustufflocation = 0x7f070015;
        public static final int sendText = 0x7f070024;
        public static final int sendmedia = 0x7f070097;
        public static final int sendmessage = 0x7f070025;
        public static final int servicerequestinterval = 0x7f0700a1;
        public static final int standard = 0x7f07007e;
        public static final int stop = 0x7f07009c;
        public static final int subscribe = 0x7f0700c4;
        public static final int tabs = 0x7f070000;
        public static final int textservice = 0x7f0700bd;
        public static final int textviewradiobutton = 0x7f0700a0;
        public static final int theme = 0x7f0700cd;
        public static final int timeinterval = 0x7f0700a4;
        public static final int timeintervallocation = 0x7f0700a9;
        public static final int trackinglocation = 0x7f070053;
        public static final int transparent_panel = 0x7f07001c;
        public static final int turnoffradiobutton = 0x7f0700aa;
        public static final int turnonradiobutton = 0x7f0700a6;
        public static final int uStuff = 0x7f070086;
        public static final int uStuffCaste = 0x7f070074;
        public static final int uStuffColor = 0x7f070012;
        public static final int uStuffCookingMethod = 0x7f0700b6;
        public static final int uStuffCourseType = 0x7f0700b8;
        public static final int uStuffCuisinetype = 0x7f0700b5;
        public static final int uStuffDietetic = 0x7f0700b7;
        public static final int uStuffDishType = 0x7f0700b9;
        public static final int uStuffFuelType = 0x7f070013;
        public static final int uStuffMainIngredient = 0x7f0700ba;
        public static final int uStuffMake = 0x7f07000f;
        public static final int uStuffMisc = 0x7f07003e;
        public static final int uStuffMiscellaneous = 0x7f0700bc;
        public static final int uStuffModel = 0x7f070010;
        public static final int uStuffOccasionOrSeason = 0x7f0700bb;
        public static final int uStuffPrice = 0x7f070014;
        public static final int uStuffRate = 0x7f07003f;
        public static final int uStuffReligion = 0x7f070073;
        public static final int uStuffRentalType = 0x7f07003d;
        public static final int uStuffStatus = 0x7f070040;
        public static final int uStuffYear = 0x7f070011;
        public static final int uStuffage = 0x7f070075;
        public static final int uStuffcolor = 0x7f070079;
        public static final int uStufffemaleradiobutton = 0x7f070077;
        public static final int uStuffgender = 0x7f07004e;
        public static final int uStuffheight = 0x7f070078;
        public static final int uStuffid = 0x7f070087;
        public static final int uStuffitemtype = 0x7f07004d;
        public static final int uStuffmaleradiobutton = 0x7f070076;
        public static final int uStuffmetaltype = 0x7f070050;
        public static final int uStuffmovielanguage = 0x7f070085;
        public static final int uStuffmovietype = 0x7f070084;
        public static final int uStuffprofile = 0x7f07000e;
        public static final int uStuffstonetype = 0x7f07004f;
        public static final int uStuffweight = 0x7f070051;
        public static final int uarea = 0x7f070016;
        public static final int ucity = 0x7f070017;
        public static final int ucountry = 0x7f070018;
        public static final int uheight = 0x7f07008a;
        public static final int uplaoaudio = 0x7f070095;
        public static final int uplaovideo = 0x7f070096;
        public static final int ustufflocation = 0x7f070041;
        public static final int uweight = 0x7f07008b;
        public static final int video = 0x7f070098;
        public static final int view = 0x7f07009e;
        public static final int widget0 = 0x7f0700c5;
        public static final int widget114 = 0x7f0700cb;
        public static final int widget127 = 0x7f07007a;
        public static final int widget27 = 0x7f0700cc;
        public static final int widget28 = 0x7f070026;
        public static final int widget29 = 0x7f070028;
        public static final int widget30 = 0x7f0700c6;
        public static final int widget31 = 0x7f07006f;
        public static final int widget32 = 0x7f070071;
        public static final int widget33 = 0x7f07006c;
        public static final int widget34 = 0x7f07001a;
        public static final int widget35 = 0x7f0700c7;
        public static final int widget39 = 0x7f07004b;
        public static final int widget40 = 0x7f070002;
        public static final int widget41 = 0x7f070045;
        public static final int widget42 = 0x7f070047;
        public static final int widget43 = 0x7f070005;
        public static final int widget46 = 0x7f07004a;
        public static final int widget56 = 0x7f070065;
        public static final int widget57 = 0x7f070066;
        public static final int widget64 = 0x7f0700c8;
        public static final int widget93 = 0x7f0700ca;
        public static final int widget94 = 0x7f070067;
        public static final int widget95 = 0x7f070068;
        public static final int zoomin = 0x7f070056;
        public static final int zoomin1 = 0x7f070090;
        public static final int zoomout = 0x7f070057;
        public static final int zoomout1 = 0x7f070091;
    }

    public static final class layout
    {
        public static final int cars = 0x7f030000;
        public static final int catalogs = 0x7f030001;
        public static final int catalogservice_controller = 0x7f030002;
        public static final int categorylist = 0x7f030003;
        public static final int chat = 0x7f030004;
        public static final int fun = 0x7f030005;
        public static final int gallery = 0x7f030006;
        public static final int help = 0x7f030007;
        public static final int home = 0x7f030008;
        public static final int install = 0x7f030009;
        public static final int jewelry = 0x7f03000a;
        public static final int locationfinder = 0x7f03000b;
        public static final int map = 0x7f03000c;
        public static final int matrimony = 0x7f03000d;
        public static final int mobeegal = 0x7f03000e;
        public static final int mobeegalactivate = 0x7f03000f;
        public static final int modes = 0x7f030010;
        public static final int movies = 0x7f030011;
        public static final int mstuff = 0x7f030012;
        public static final int mstuffsearch = 0x7f030013;
        public static final int mstuffsearchresults = 0x7f030014;
        public static final int mstufftextview = 0x7f030015;
        public static final int multimedia = 0x7f030016;
        public static final int playmedia = 0x7f030017;
        public static final int preferences = 0x7f030018;
        public static final int response = 0x7f030019;
        public static final int restaurants = 0x7f03001a;
        public static final int settings = 0x7f03001b;
        public static final int showmap = 0x7f03001c;
        public static final int subscribe = 0x7f03001d;
        public static final int textlocation = 0x7f03001e;
        public static final int theme = 0x7f03001f;
        public static final int time_settings = 0x7f030020;
    }

    public static final class string
    {
        public static final int CatalogServer = 0x7f060029;
        public static final int ChatServer = 0x7f060028;
        public static final int LocationRequest = 0x7f06002a;
        public static final int MediaServer = 0x7f060027;
        /**
         * Use this IP for internet user 59.92.89.234 For local user IP is
         * 192.168.1.68
         */
        public static final int RemoteServer = 0x7f060026;
        public static final int ShowMessage = 0x7f06002b;
        public static final int app_name = 0x7f060002;
        public static final int catalogs = 0x7f06000a;
        public static final int chat = 0x7f06000e;
        public static final int delete = 0x7f06000f;
        public static final int done = 0x7f060012;
        public static final int donequery = 0x7f06001e;
        public static final int editquery = 0x7f060018;
        public static final int exits = 0x7f06000d;
        public static final int faq = 0x7f060034;
        public static final int faq1 = 0x7f060035;
        public static final int faq10 = 0x7f06003e;
        public static final int faq11 = 0x7f06003f;
        public static final int faq12 = 0x7f060040;
        public static final int faq13 = 0x7f060041;
        public static final int faq14 = 0x7f060042;
        public static final int faq15 = 0x7f060043;
        public static final int faq16 = 0x7f060044;
        public static final int faq17 = 0x7f060045;
        public static final int faq18 = 0x7f060046;
        public static final int faq2 = 0x7f060036;
        public static final int faq3 = 0x7f060037;
        public static final int faq4 = 0x7f060038;
        public static final int faq5 = 0x7f060039;
        public static final int faq6 = 0x7f06003a;
        public static final int faq7 = 0x7f06003b;
        public static final int faq8 = 0x7f06003c;
        public static final int faq9 = 0x7f06003d;
        public static final int favorite = 0x7f06001d;
        /**
         * Main Profile
         */
        public static final int help = 0x7f060030;
        public static final int helpalert = 0x7f060047;
        public static final int helpbroadcast = 0x7f060049;
        public static final int helpinteraction = 0x7f060048;
        public static final int helppartner = 0x7f060032;
        public static final int helpprofile = 0x7f060031;
        public static final int helpservice = 0x7f060033;
        public static final int hint = 0x7f060006;
        public static final int hit = 0x7f060005;
        public static final int ignore = 0x7f06001c;
        public static final int mapview = 0x7f06001a;
        /**
         * menu String
         */
        public static final int mstuffs = 0x7f060009;
        public static final int newquery = 0x7f060013;
        public static final int notification_cancel = 0x7f060025;
        public static final int notification_message = 0x7f060024;
        public static final int notifying_service_controller = 0x7f060004;
        public static final int noviewquery = 0x7f06001f;
        public static final int partner = 0x7f06002f;
        public static final int remote_service_label = 0x7f060023;
        public static final int remote_service_started = 0x7f060021;
        public static final int remote_service_stopped = 0x7f060022;
        public static final int results_view_preferences = 0x7f060000;
        public static final int satelliteview = 0x7f06001b;
        public static final int search = 0x7f06000c;
        public static final int setthemes = 0x7f060011;
        public static final int settings = 0x7f06000b;
        public static final int shareaudio = 0x7f060016;
        public static final int shareimage = 0x7f060015;
        public static final int sharemedia = 0x7f060014;
        public static final int sharevideo = 0x7f060017;
        public static final int start_service = 0x7f060007;
        /**
         * menu String
         */
        public static final int status_bar_notifications_clear = 0x7f060020;
        public static final int stop_service = 0x7f060008;
        public static final int summary_mapview_preference = 0x7f060001;
        /**
         * partner profile
         */
        public static final int textage = 0x7f06002c;
        public static final int textheight = 0x7f06002d;
        public static final int textview = 0x7f060019;
        public static final int textweight = 0x7f06002e;
        public static final int viewquery = 0x7f060010;
        public static final int welcome = 0x7f060003;
    }

    public static final class xml
    {
        public static final int preferences = 0x7f040000;
    }
}
