/*
 * This source file was generated by the Gradle 'init' task
 */
package org.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'license' plugin.
 */
class LicensePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("license", LicenseTask::class.java) { task ->
            task.description = "add a license header to source code"   // Add description
            task.group = "from license plugin"                         // Add group
            task.doLast {
                println("Hello from plugin 'org.plugin.license'")
            }
        }
    }
}

